# Generated by Django 3.1.6 on 2023-10-13 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('type', models.CharField(default='post', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('id', models.URLField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('source', models.URLField()),
                ('origin', models.URLField()),
                ('description', models.CharField(max_length=255)),
                ('contentType', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('categories', models.CharField(blank=True, max_length=255)),
                ('count', models.PositiveIntegerField()),
                ('comments', models.URLField()),
                ('published', models.DateTimeField()),
                ('visibility', models.CharField(max_length=10)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author')),
            ],
        ),
    ]
