# Generated by Django 3.1.6 on 2023-10-06 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_author_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='display_name',
            new_name='displayName',
        ),
    ]
