# Generated by Django 3.1.6 on 2023-10-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(null=True),
        ),
    ]
